### ISSUE TITLE
ERROR: Publish permissions: '[publish_actions]' weren't accepted by user

### ISSUE THREAD

**Issue by achinverma** [sromku/android-simple-facebook#187]
HI, i am using this demo, but when i click to publish photo i 'm getting errors, anyone guides me?

06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242): ERROR: Publish permissions: '[publish_actions]' weren't accepted by user
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242): java.lang.Throwable
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at com.sromku.simple.fb.utils.Logger.getStackTrace(Logger.java:69)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at com.sromku.simple.fb.utils.Logger.logError(Logger.java:55)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at com.sromku.simple.fb.actions.PublishAction$1.onNotAcceptingPermissions(PublishAction.java:75)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at com.sromku.simple.fb.SessionManager$SessionStatusCallback.call(SessionManager.java:515)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at com.facebook.Session$4$1.run(Session.java:1542)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at android.os.Handler.handleCallback(Handler.java:733)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at android.os.Handler.dispatchMessage(Handler.java:95)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at android.os.Looper.loop(Looper.java:136)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at android.app.ActivityThread.main(ActivityThread.java:5001)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at java.lang.reflect.Method.invokeNative(Native Method)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at java.lang.reflect.Method.invoke(Method.java:515)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
06-24 16:46:46.648: E/com.sromku.simple.fb.actions.PublishAction(12242):    at dalvik.system.NativeStart.main(Native Method)

**Comment by RyanHsueh** [comment]
Hi all, 
I got the same issue, too.

03-12 11:00:31.652 I/MXW﹕ 00 01 15 268  [RYAN] performFBPublish > onFail  : Publish permissions: '[publish_actions]' weren't accepted by user

I already accepted publish permission! 
And I set up publish_action in configuration, too

// ++++++++++++
private void initSimpleFacebook() {
        Permission[] permissions = new Permission[] {
                Permission.USER_PHOTOS,
                Permission.EMAIL,
                Permission.PUBLISH_ACTION
        };

        SimpleFacebookConfiguration configuration = new SimpleFacebookConfiguration.Builder()
                .setAppId(getString(R.string.app_facebook_id))
                .setNamespace(FB_NAME_SPACE)
                .setPermissions(permissions)
                .build();

        SimpleFacebook.setConfiguration(configuration);
    }
// --------------

I can login but publish failed
Please help!

**Comment by stephendaniel** [comment]
Hi RyanHsueh,

Have you submitted the "publish_action" permission to facebook? My problem is solved after I submitted the "publish_action" permission in my app facebook developer page. Your approved item permission should looked like this one 
![capture](https://cloud.githubusercontent.com/assets/10130399/6612612/25f2b4cc-c8b2-11e4-885a-104b8b810bed.PNG)

**Comment by ananarola** [comment]
Hi.. I have the similar problem too. I also approved publish action permission from facebook but still getting same error

ERROR: Publish permissions: '[publish_actions, publish_stream]' weren't accepted by user
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): java.lang.Throwable
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at com.sromku.simple.fb.utils.Logger.getStackTrace(Logger.java:69)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at com.sromku.simple.fb.utils.Logger.logError(Logger.java:55)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at com.sromku.simple.fb.actions.PublishAction$1.onNotAcceptingPermissions(PublishAction.java:76)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at com.sromku.simple.fb.SessionManager$SessionStatusCallback.call(SessionManager.java:517)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at com.facebook.Session$3$1.run(Session.java:1302)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at android.os.Handler.handleCallback(Handler.java:730)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at android.os.Handler.dispatchMessage(Handler.java:92)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at android.os.Looper.loop(Looper.java:137)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at java.lang.reflect.Method.invoke(Method.java:525)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
05-15 02:01:47.630: E/com.sromku.simple.fb.actions.PublishAction(1613): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by ananarola** [comment]
Can anyone help me for that :  I am configuring app like
SimpleFacebookConfiguration configuration = new SimpleFacebookConfiguration.Builder()
		.setAppId(APP_ID)
		.setNamespace(APP_NAMESPACE)
		.setPermissions(permissions)
		.setDefaultAudience(SessionDefaultAudience.FRIENDS)
		.build();
		SimpleFacebook.setConfiguration(configuration);
